---
title: "final_prediction.rmd"
author: "Miroslav Bergam"
date: "10/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

```{r, warning = FALSE, message = FALSE}

polls_historical <- read_csv("../data/pollavg_bystate_1968-2016.csv") %>% 
  
  # Excluding early polls (taken before convention) 
  
  filter(before_convention == FALSE) %>%
  group_by(year, state, party) %>% 
  summarize(average_poll = mean(avg_poll)) %>% 
  filter(year >= 1988) %>%
  mutate(party = case_when(
    party == "democrat" ~ "D",
    party == "republican" ~ "R"
  ))

elections_historical <- read_csv("../data/popvote_bystate_1948-2016.csv") %>%
  select(state, year, R_pv2p, D_pv2p) %>% 
  pivot_longer(R_pv2p:D_pv2p, names_to = "party", values_to = "pv2p") %>% 
  mutate(party = case_when(
    party == "D_pv2p" ~ "D",
    party == "R_pv2p" ~ "R"
  )) %>% 
  group_by(state, party) %>% 
  mutate(last_election = lag(pv2p, order_by = year)) %>% 
  drop_na() %>%
  filter(year >= 1988)

incumbency_historical <- read_csv("../data/popvote_1948-2016.csv") %>%
  filter(year >= 1988) %>%
  mutate(party = case_when(
    party == "democrat" ~ "D",
    party == "republican" ~ "R"
  )) %>%
  select(year, party, winner, incumbent, incumbent_party) %>%
  drop_na()

approval <- read_csv("../data/approval_1941-2020.csv") %>%
  group_by(president) %>%
  arrange(desc(poll_enddate)) %>%
  filter(row_number() %in% c(1,2,3,4,5)) %>%
  ungroup() %>%
  group_by(year) %>%
  summarize(approval = mean(approve)) %>%
  filter(year != 2020)

final <- polls_historical %>%
  left_join(elections_historical, by = c("party", "state", "year")) %>%
  left_join(incumbency_historical, by = c("year", "party")) %>%
  left_join(approval, by = "year") %>%
  drop_na()


model = lm(pv2p ~ incumbent + incumbent_party + average_poll + last_election + approval, data = final)

summary(model)

tab_model(model,
          title = "Modeling Presidential Voteshare by State",
          dv.labels = "Candidate's Projected State Voteshare")

png("../figures/summarytable.png", height=1000, width=200)

```

```{r, warning = FALSE, message = FALSE}

polls_new <- read_csv("../data/polls_recent.csv") %>%
  mutate(end_date = as.Date(end_date, "%m/%d/%y")) %>% 
  
  # Filtering for polls since the first presidential debate
  
  filter(end_date >= "2020-09-28") %>% 
  group_by(candidate_party, state) %>% 
  summarize(average_poll = mean(pct)) %>% 
  ungroup() %>%
  filter(candidate_party == "DEM" | candidate_party ==  "REP") %>% 
  mutate(party = case_when(
    candidate_party == "DEM" ~ "D",
    candidate_party == "REP" ~ "R"
  )) %>% 
  select(!candidate_party) 

elections_new <- elections_historical %>%
  filter(year == 2016) %>%
  mutate(last_election = pv2p) %>%
  select(state, party, last_election)

approval_new <- read_csv("../data/approval_1941-2020.csv") %>%
  group_by(president) %>%
  arrange(desc(poll_enddate)) %>%
  filter(row_number() %in% c(1,2,3,4,5)) %>%
  ungroup() %>%
  group_by(year) %>%
  summarize(approval = mean(approve)) %>%
  filter(year == 2020) %>%
  select(approval) %>%
  pull()

data_new <- polls_new %>% 
  left_join(elections_new, by = c("state", "party")) %>% 
  mutate(incumbent = case_when(
           party == "R" ~ TRUE,
           party == "D" ~ FALSE
         )) %>%
  mutate(incumbent_party = incumbent) %>%
  mutate(approval = approval_new) %>%
  drop_na() %>%
  filter(party == "R")

electoral_college <- read_csv("../data/ec_1952-2020.csv") %>%
  filter(year == 2020,
         state != "Total") 

predictions <- predict(model, 
                      newdata = data_new,
                      type ="response") 

predictions <- data_frame(predictions)

abbrev <- read_csv("../data/abbrev.csv") %>%
  select(State, Code) %>%
  rename(state = State) %>%
  left_join(electoral_college, by = "state") %>%
  mutate(electors = case_when(
    state == "District of Columbia" ~ 3,
    TRUE ~ electors
  )) %>%
  select(Code, electors) %>%
  rename(state = Code)

states <- abbrev %>%
  select(state)

prediction_df <- cbind(predictions, states) %>%
  mutate(winner = ifelse(predictions < 50, "Biden", "Trump")) %>%
  mutate(margin = predictions - 50) %>%
  mutate(group = case_when(
           margin >= 5 ~ "Trump",
           margin >= 2 ~ "Likely Trump",
           margin <= -5 ~ "Biden",
           margin <= -2 ~ "Likely Biden",
           (margin > -2 & margin < 2) ~ "Toss-Up"
         )) %>%
  left_join(abbrev, by = "state")

```

```{r, warning = FALSE, message = FALSE}

prediction_df %>% 
  ggplot(aes(state = state, fill = group)) +
  geom_statebins() +
  theme_statebins() +
  labs(title = "2020 Presidential Election State-Level Predictions",
       fill = "",
       caption = "Sources: The New York Times, Gallup, Five-Thirty-Eight") +
  scale_fill_manual(values = c("#619CFF", "#C3D7F7", "#BABABA", "#FACECA", "#F8766D"),
                    breaks = c("Biden", "Likely Biden", "Toss-Up", "Likely Trump", "Trump"))

ggsave("../figures/finalpredmap.jpg", height = 4, width = 6)

 prediction_df %>%
  group_by(group) %>%
  summarise(ev = sum(electors)) %>%
  ggplot(aes(x = "1", y = ev, fill = fct_relevel(group, "Trump", "Likely Trump", "Toss-Up", "Likely Biden", "Biden"), label = ev)) +
  geom_col(show.legend = FALSE, width = 0.25) + 
  geom_text(position = position_stack(vjust = 0.5)) +
  coord_flip() + 
  theme_void() + 
  labs(fill = "") +
  scale_fill_manual(values = c("#619CFF", "#C3D7F7", "#BABABA", "#FACECA", "#F8766D"),
                    breaks = c("Biden", "Likely Biden", "Toss-Up", "Likely Trump", "Trump"))
  
ggsave("../figures/finalelectoral.jpg", height = 4, width = 6)
  
```



```{r}

library(gt)

predictions_table <- predict(model, 
                      newdata = data_new,
                      type ="response",
                      interval = "confidence") 

predictions_table <- as.data.frame(predictions_table)

predictions_table <- cbind(predictions_table, states) %>%
  mutate(winner = ifelse(predictions < 50, "Biden", "Trump")) %>%
  mutate(margin = fit - 50) %>%
  mutate(`lower bound` = lwr - 50) %>%
  mutate(`upper bound` = upr - 50) %>%
  left_join(abbrev, by = "state")

finaltable <- predictions_table %>% 
  select(state, margin, `lower bound`, `upper bound`) %>%
  gt() %>%
  tab_header(title = md("**Trump's Predicted Win and Loss Margins by State**"))

gtsave(finaltable, "../figures/finaltable.html")

```




