---
title: "blog 3 graphics"
author: "Miroslav Bergam"
date: "9/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading necessary packages

library(tidyverse)
library(ggplot2)
library(cowplot)
library(broom)
library(infer)
library(gt)
```

```{r data cleaning, warning = FALSE, message = FALSE}

# Reading in data 

poll_2016 <- read_csv("../data/polls_2016.csv") %>%
  select(pollster, adjpoll_clinton, adjpoll_trump, poll_wt) %>%
  unique()

poll_2020 <- read_csv("../data/polls_2020.csv") %>%
  select(pollster, candidate_name, candidate_party, pct) %>%
  unique()

poll_rating_2019 <- read_csv("../data/poll_ratings_2019.csv") %>%
  select(`538 Grade`, Pollster)

poll_rating_2014 <- read_tsv("../data/poll_ratings_2014.tsv") %>%
  select(`538 Grade`, Pollster)

# Joining 2020 and 2016 poll ratings and cleaning data
# Dropping NAs so that the only polls are ones present in both datasets

poll_ratings <- poll_rating_2019 %>%
  left_join(poll_rating_2014, by = "Pollster") %>%
  mutate(rating_2014 = `538 Grade.y`,
         rating_2019 = `538 Grade.x`,
         pollster = Pollster) %>%
  select(pollster, rating_2014, rating_2019) %>%
  drop_na() %>%
  mutate(rating_2019 = dplyr::recode(rating_2019,
                `B/C°` = "B/C")) %>%
  mutate(rating_2019 = dplyr::recode(rating_2019,
                `C/D°` = "C/D")) %>%
  mutate(rating_2019 = dplyr::recode(rating_2019,
                `A/B°` = "A/B"))

# Ordering these so that the columns are in the correct order

poll_ratings$rating_2014 <- factor(poll_ratings$rating_2014, 
                                   levels = c("A+", "A", "A-", "B+", "B", "B-",
                                              "C+", "C", "C-", "D+", "D", "D-", "F"))

poll_ratings$rating_2019 <- factor(poll_ratings$rating_2019, 
                                   levels = c("A+", "A", "A-", "A/B", "B+", "B", "B-", "B/C",
                                              "C+", "C", "C-", "C/D", "D", "F"))

```

```{r poll ratings}

# 2016 ratings graph

graph1 <- ggplot(poll_ratings, aes(x = rating_2014, fill = rating_2014)) +
  geom_bar() +
  theme(legend.position = "none") + 
  labs(title = "Ratings Before 2016 Election",
       x = "Pre-2016 Poll Ratings",
       y = "Count",
       caption = "Source: Five-Thirty-Eight")

# 2020 ratings graph

graph2 <- ggplot(poll_ratings, aes(x = rating_2019, fill = rating_2019)) +
  geom_bar() +
  theme(legend.position = "none") + 
  labs(title = "Ratings Before 2020 Election",
       x = "Pre-2020 Poll Ratings",
       y = "Count",
       caption = "Source: Five-Thirty-Eight")

plot_grid(graph1, graph2)

# Rating changes graph

ggsave("../figures/poll_ratings_cowplot.jpg", height = 4, width = 6)

ggplot(poll_ratings, aes(x = rating_2014, fill = rating_2019)) +
  geom_bar() +
  labs(title = "Updated Poll Ratings Across Elections",
       x = "Pre-2016 Poll Ratings",
       y = "Count",
       fill = "Pre-2020 Poll Ratings",
       caption = "Source: Five-Thirty-Eight")

ggsave("../figures/updated_poll_ratings.jpg", height = 4, width = 6)

```

```{r weighting}

# Assigning each letter grade a number that will later be turned into a weight
# such that A+s are weighted most heavily and Fs are rated worst

poll_ratings <- poll_ratings %>% 
  mutate(rating_2014 = case_when(
    rating_2014 == "A+" ~ 13,
    rating_2014 == "A" ~ 12,
    rating_2014 == "A-" ~ 11,
    rating_2014 == "B+" ~ 10,
    rating_2014 == "B" ~ 9,
    rating_2014 == "B-" ~ 8,
    rating_2014 == "C+" ~ 7,
    rating_2014 == "C" ~ 6,
    rating_2014 == "C-" ~ 5,
    rating_2014 == "D+" ~ 4,
    rating_2014 == "D" ~ 3,
    rating_2014 == "D-" ~ 2,
    rating_2014 == "F" ~ 1
  )) %>%
  mutate(rating_2019 = case_when(
    rating_2019 == "A+" ~ 14,
    rating_2019 == "A" ~ 13,
    rating_2019 == "A-" ~ 12,
    rating_2019 == "A/B" ~ 11,
    rating_2019 == "B+" ~ 10,
    rating_2019 == "B" ~ 9,
    rating_2019 == "B-" ~ 8,
    rating_2019 == "B/C" ~ 7,
    rating_2019 == "C+" ~ 6,
    rating_2019 == "C" ~ 5,
    rating_2019 == "C-" ~ 4,
    rating_2019 == "C/D" ~ 3,
    rating_2019 == "D" ~ 2,
    rating_2019 == "F" ~ 1
  ))

# Joining poll ratings and 2020 polling data

final_df <- poll_2020 %>%
  left_join(poll_ratings, by = "pollster") %>%
  drop_na() %>%
  filter(candidate_party == "REP")

```

```{r bootstrap, warning = FALSE, message = FALSE}

# bootstrapping with the replacement 

bootstrap_data_2019 <- final_df %>%
  rep_sample_n(size = 100, reps = 100, replace = TRUE) %>%
  
  # Calculating weights
  
  mutate(wt_2019 = rating_2019/sum(rating_2019),
         wt_2014 = rating_2014/sum(rating_2014)) %>%
  
  # Weighting each prediction based on the pollster's assigned weight
  
  mutate(wt_pred = pct * wt_2019) %>%
  
  # Adding them up to get final point estimate prediction
  # Final DF should be a point estimate for each replicate of bootstrap
  
  summarise(sum = sum(wt_pred))

# Calculating error margin from the replicates to create upper and lower bound

error_2019 <- qt(0.975,df=length(bootstrap_data_2019$sum)-1)*sd(bootstrap_data_2019$sum)/sqrt(length(bootstrap_data_2019$sum))

# Calculating lower and higher bounds

low_2019 <- mean(bootstrap_data_2019$sum)-error_2019

high_2019 <- mean(bootstrap_data_2019$sum)+error_2019

# Doing the same bootstrapping process for 2016 weights

bootstrap_data_2014 <- final_df %>%
  rep_sample_n(size = 100, reps = 100, replace = TRUE) %>%
  mutate(wt_2019 = rating_2019/sum(rating_2019),
         wt_2014 = rating_2014/sum(rating_2014)) %>%
  mutate(wt_pred = pct * wt_2014) %>%
  summarise(sum = sum(wt_pred))

error_2014 <- qt(0.975,df=length(bootstrap_data_2014$sum)-1)*sd(bootstrap_data_2014$sum)/sqrt(length(bootstrap_data_2014$sum))

low_2014 <- mean(bootstrap_data_2014$sum)-error_2014

high_2014 <- mean(bootstrap_data_2014$sum)+error_2014

intervals <- tibble(labels = c("Pre-2016 Poll Weights", "Pre-2020 Poll Weights"),
                    lower = c(low_2014, low_2019),
                    prediction = c(wt_2014_pred, wt_2019_pred),
                    upper = c(high_2014, high_2019))

intervals %>%
  gt() %>%
  
  # Titling the table
  
  tab_header(title = "Trump's Predicted Voteshare in 2020 Presidential Election", 
             subtitle = "95% Confidence Intervals")%>%
  
  # Labeling the columns
  
  cols_label(
    labels = md(" "),
    lower = md("**Lower**"),
    prediction = md("**Prediction**"),
    upper = md("**Upper**")) %>%
  
  # Adding footnote 
  
  tab_source_note(md("Source: Five-Thirty-Eight"))

gtsave(interval_table, "../figures/intervals_table.html")


```

```{r interval plot}

intervals %>%
  select(lower, prediction, upper) %>%
  ggplot(aes())

```

```{r}

data <- read_csv("../data/popvote_1948-2016.csv")

```


