---
title: "Blog 2"
author: "Mirosgav Bergam"
date: "9/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Importing packages
library(tidyverse)
library(mefa) #for fill_na()
library(useful)

```

```{r Reading-Data, warning = FALSE, message = FALSE}

# Reading in data and filtering for the first two quarters of each election year
# Then averaging the unemployment during that period for each year

ga_data <- read_csv("../data/local.csv") %>%
  filter(`State and area` == "Georgia",
         Month %in% c('01', '02', '03', '04', '05', '06', '07', '08')) %>%
  group_by(Year) %>%
  summarise(unemployment = mean(Unemployed_prce)) %>%
  mutate(year = Year) %>%
  select(year, unemployment)

us_data <- read_csv("../data/econ.csv") %>%
  drop_na() %>%
  filter(quarter == 2 | quarter == 1) %>%
  group_by(year) %>%
  summarise(unemployment = mean(unemployment)) %>%
  select(unemployment, year)

```

```{r Data-Cleaning, warning = FALSE, message = FALSE}

# Reading in CSV of US Presidents to get their parties

incumbent <- read_csv("../data/presidents.csv") %>%
  select(Party, office) %>%
  separate(office, into = c("junk", "junk2", "year"), sep = "/") %>%
  mutate(party = Party,
         year = as.numeric(year),
         year = year - 1) %>%
  select(year, party) 

# Joining unemployment data and voting data

ga_voting <- read_csv("../data/popvote_bystate_1948-2016.csv") %>%
  filter(state == "Georgia") %>%
  left_join(incumbent, by = "year")

# Filling in NA values with the value above it for years where
# there was not an incumbent. Incumbent column now refers to
# incumbent party, not candidate
  
ga_voting <- fill.na(ga_voting) %>%
  arrange(year)

# Shifting incumbents up by one so that they correspond to election years

ga_voting <- shift.column(data = ga_voting, columns = "party", up = FALSE, len = 1)

# Joining all data together

ga_voting <- ga_voting %>%
  mutate(incumbent = party.Shifted) %>%
  mutate(incumbent_voteshare = case_when(
    incumbent == "Republican" ~ R_pv2p,
    incumbent == "Democratic" ~ D_pv2p
  )) %>%
  select(year, incumbent_voteshare, incumbent) %>%
  left_join(ga_data, by = "year") %>%
  mutate(ga_unemployment = unemployment) %>%
  select(!unemployment) %>%
  left_join(us_data, by = "year") %>%
  mutate(us_unemployment = unemployment) %>%
  select(!unemployment) %>%
  drop_na()

```

```{r Plot1}

# First plot: GA unemployment by GA incumbent voteshare

ga_voting %>%
  ggplot(aes(x = ga_unemployment , y = incumbent_voteshare)) +
  geom_point() + 
  geom_smooth(method = "lm") +  
  geom_text(aes(label = year, hjust=-0.1, vjust=1.1)) + 
  labs(title = "Incumbent Voteshare in Georgia by Georgia Unemployment",
       subtitle = "There exists a weak, negative correlation",
       x = "Georgia Election Year Q1 and Q2 Unemployment Rate (%)",
       y = "Incumbent 2-Party Voteshare in Georgia (%)",
       caption = "Source: US Bureau of Labor Statistics")

ggsave("../figures/GAunemployed.jpg", height = 4, width = 6)

```


```{r Plot2}

# Second plot: US unemployment by GA incumbent voteshare

ga_voting %>%
  ggplot(aes(x = us_unemployment, y = incumbent_voteshare, label = year)) +
  geom_point() + 
  geom_text(aes(label = year, hjust=-0.1, vjust=1.1)) + 
  geom_smooth(method = "lm") +
  labs(title = "Incumbent Voteshare in Georgia by U.S. Unemployment",
       subtitle = "There exists a very weak, negative correlation",
       x = "U.S. Election Year Q1 and Q2 Unemployment Rate (%)",
       y = "Incumbent 2-Party Voteshare in Georgia (%)",
       caption = "Source: US Bureau of Labor Statistics")


ggsave("../figures/usunemployed.jpg", height = 4, width = 6)

```

```{r Plot3}

# Third plot: GA unemployment by GA incumbent voteshare, coloring by party

ga_voting %>%
  ggplot(aes(x = ga_unemployment, y = incumbent_voteshare, label = year, color = incumbent)) +
  geom_point() + 
  geom_text(aes(label = year, hjust=-0.1, vjust=1.1)) + 
  geom_smooth(method = "lm") +
  scale_color_manual(values = c("Democratic" = "blue", 
                                "Republican" = "red")) + 
  labs(title = "Incumbent Voteshare in Georgia by Georgia Unemployment",
       subtitle = "Negative correlation is present for Republicans, but not Democrats",
       x = "Georgia Election Year Q1 and Q2 Unemployment Rate (%)",
       y = "Incumbent 2-Party Voteshare in Georgia (%)",
       caption = "Source: US Bureau of Labor Statistics",
       color = "Incumbent Party")

ggsave("../figures/GAunemployed_party.jpg", height = 4, width = 6)

```

```{r Plot4}

# Fourth plot: US unemployment by GA incumbent voteshare, coloring by party

ga_voting %>%
  ggplot(aes(x = us_unemployment, y = incumbent_voteshare, label = year, color = incumbent)) +
  geom_point() + 
  geom_text(aes(label = year, hjust=-0.1, vjust=1.1)) + 
  geom_smooth(method = "lm") +
  scale_color_manual(values = c("Democratic" = "blue", 
                                "Republican" = "red")) + 
  labs(title = "Incumbent Voteshare in Georgia by U.S. Unemployment",
       subtitle = "Negative correlation is present for Republicans, but not Democrats",
       x = "U.S. Election Year Q1 and Q2 Unemployment Rate (%)",
       y = "Incumbent 2-Party Voteshare in Georgia (%)",
       caption = "Source: US Bureau of Labor Statistics",
       color = "Incumbent Party")


ggsave("../figures/usunemployed_party.jpg", height = 4, width = 6)

```

```{r stats1}

# Printing summary stats

ga <- lm(incumbent_voteshare ~ ga_unemployment, data = ga_voting)

us <- lm(incumbent_voteshare ~ us_unemployment, data = ga_voting)

summary(ga)

summary(us)

```

```{r stats2}

# Printing summary stats

ga_reps <- ga_voting %>%
  filter(incumbent == "Republican")

ga_dems <- ga_voting %>%
  filter(incumbent == "Democratic")

ga_dems_model <- lm(incumbent_voteshare ~ ga_unemployment, data = ga_dems)

ga_rep_model <- lm(incumbent_voteshare ~ ga_unemployment, data = ga_reps)

summary(ga_rep_model)

```

```{r states3}

# Printing summary stats

us_reps <- ga_voting %>%
  filter(incumbent == "Republican")

us_dems <- ga_voting %>%
  filter(incumbent == "Democratic")

us_dems_model <- lm(incumbent_voteshare ~ us_unemployment, data = ga_dems)

us_rep_model <- lm(incumbent_voteshare ~ us_unemployment, data = ga_reps)

summary(us_rep_model)

```

```{r newdata}

# Predicting new data

newdata <- data.frame(ga_unemployment = c(6.7))

predict(ga_rep_model, newdata = newdata, interval = "prediction")

```







