---
title: "blog 4 graphs"
author: "Miroslav Bergam"
date: "10/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Reading in necessary packages
library(tidyverse)
library(mefa) #for fill_na()
library(useful)
library(sjPlot)
library(gt)

```

```{r data-cleaning, warning = FALSE, message = FALSE}

# Reading in CSV of US Presidents to get their parties

incumbent <- read_csv("../data/presidents.csv") %>%
  select(Party, office) %>%
  separate(office, into = c("junk", "junk2", "year"), sep = "/") %>%
  mutate(party = Party,
         year = as.numeric(year),
         year = year - 1) %>%
  select(year, party) 

incumbent <- shift.column(data = incumbent, column = "party", up = FALSE, len = 1) %>%
  mutate(incumbent_party = party.Shifted) %>%
  select(year,incumbent_party)

# Joining with popular vote dara

pop_vote_state <- read_csv("../data/popvote_bystate_1948-2016.csv") %>%
  pivot_longer(cols = R_pv2p:D_pv2p,
               names_to = "Party",
               values_to = "2pvs") %>%
  left_join(incumbent, by = "year") %>%
  arrange(desc(year)) %>%
  filter(year != 1948 & year != 2016 & year != 2012) %>%
  mutate(party = case_when(
    Party == "R_pv2p" ~ "Republican",
    Party == "D_pv2p" ~ "Democratic"))

# Filling in NA values with the value above it for years where
# there was not an incumbent. Incumbent column now refers to
# incumbent party, not candidate
  
pop_vote_state <- fill.na(pop_vote_state) 

# Joining with state abbreviations to join with other data later

abbrev <- read_csv("../data/abbrev.csv") %>%
  mutate(state = State)

pop_vote_state <- pop_vote_state %>%
  left_join(abbrev, by = "state") %>%
  unite(join, c(Code, year), sep = "", remove = FALSE) %>%
  select(state, year, party, `2pvs`, incumbent_party, join)

# Joining with federal grant data in election years

fed_grants_state <- read_csv("../data/fedgrants_bystate_1988-2008.csv") %>%
  filter(elxn_year == 1) %>%
  arrange(state_abb) 

fed_grants_state <- shift.column(data = fed_grants_state, column = "grant_mil", up = FALSE, len = 1)

fed_grants_state <- fed_grants_state %>%
  mutate(perc_change = (grant_mil - grant_mil.Shifted)/grant_mil.Shifted * 100) %>%
  unite(join, c(state_abb, year), sep = "", remove = TRUE) %>%
  select(join, perc_change)

pop_vote_state <- pop_vote_state %>%
  left_join(fed_grants_state, by = "join") %>%
  drop_na() %>%
  mutate(incumbent = case_when(
    party == incumbent_party ~ TRUE,
    party != incumbent_party ~ FALSE))

# Joining with data on swing states from each election

swing <- read_csv("../data/fedgrants_bystate_1988-2008.csv") %>%
  unite(join, c(state_abb, year), sep = "", remove = TRUE) %>%
  separate(state_year_type, into = c("swing", "junk2")) %>%
  select(join, swing)

pop_vote_state <- pop_vote_state %>%
  left_join(swing, by = "join") %>%
  mutate(swing = case_when(
    swing == "swing" ~ TRUE,
    swing == "core" ~ FALSE,
    swing == NA ~ FALSE)) %>%
  filter(year != 1984)

pop_vote_state["swing"][is.na(pop_vote_state["swing"])] <- FALSE

```

```{r, warning = FALSE, message = FALSE}

# Creating model

model <- lm(`2pvs` ~ incumbent * perc_change * swing, data = pop_vote_state) 

summary(model) 

tab_model(model)

png("../figures/incumbent_table.png", height=1000, width=200)

```

```{r, warning= FALSE, message = FALSE}

pop_vote_state %>%
  filter(incumbent == TRUE) %>% 
  ggplot(aes(x = perc_change, y = `2pvs`)) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  labs(x = "% Change in Election-Year Federal Grants",
       y = "Incumbent Two-Party Voteshare",
       title = "State-level Incumbent Voteshares by Federal Grants",
       caption = "Source: Kriner and Reeves, 2012")

ggsave("../figures/incumbent_grants.jpg", height = 4, width = 6)

```
```{r}

pop_vote_state %>%
  filter(incumbent == TRUE) %>% 
  ggplot(aes(x = swing, y = `2pvs`, fill = swing)) + 
  geom_boxplot() +
  labs(x = "Swing state?",
       y = "Incumbent Two-Party Voteshare",
       title = "State-Level Incumbent Voteshare for Swing States", 
       subtitle = "Swing states defined on election-to-election basis",
       caption = "Source: Kriner and Reeves, 2012") +
  theme(legend.position = "none")

ggsave("../figures/incumbent_swing.jpg", height = 4, width = 6)

```


```{r}

pop_vote_state %>%
  ggplot(aes(x = incumbent, y = `2pvs`, fill = incumbent)) + 
  geom_boxplot() + 
  labs(x = "Incumbent candidate?",
       y = "State-Level Two-Party Voteshare",
       title = "State-level Incumbent vs. Non-Incumbent Voteshares") + 
  theme(legend.position = "none")

ggsave("../figures/incumbent_box.jpg", height = 4, width = 6)

```





